development:
  server: "http://xxxx:9292/faye"
  secret_token: "secret"
test:
  server: "http://xxxx:9292/faye"
  secret_token: "secret"
production:
  server: "http://xxxx:9292/faye"
  secret_token: "xxxxxxxxxxxxxxxxxx"
  signature_expiration: 3600 # one hour
