# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Organization.create(:name => "My Organization",:email => "myorg@test.com",:website=>"www.test.com",:total_users=>10,:size_id => 3, :is_active => true)

TaskType.create(:name => "Call",:organization_id => 1)
TaskType.create(:name => "Skype",:organization_id => 1)
TaskType.create(:name => "Email",:organization_id => 1)

CompanyStrength.create(range: '1-10')
CompanyStrength.create(range: '11-50')
CompanyStrength.create(range: '51-200')
CompanyStrength.create(range: '201-500')
CompanyStrength.create(range: '501-1000')
CompanyStrength.create(range: '>1000')
Country.create(ccode: 'AF',name: 'Afghanistan',isd_code: '93',flag: 'AF.png')
Country.create(ccode: 'AX',name: 'Aland Islands',isd_code: '358',flag: 'AX.png')
Country.create(ccode: 'AL',name: 'Albania',isd_code: '355',flag: 'AL.png')
Country.create(ccode: 'DZ',name: 'Algeria',isd_code: '213',flag: 'DZ.png')
Country.create(ccode: 'AS',name: 'American Samoa',isd_code: '1+684',flag: 'AS.png')
Country.create(ccode: 'AD',name: 'Andorra',isd_code: '376',flag: 'AD.png')
Country.create(ccode: 'AO',name: 'Angola',isd_code: '244',flag: 'AO.png')
Country.create(ccode: 'AI',name: 'Anguilla',isd_code: '1+264',flag: 'AI.png')
Country.create(ccode: 'AQ',name: 'Antarctica',isd_code: '672',flag: 'AQ.png')
Country.create(ccode: 'AG',name: 'Antigua and Barbuda',isd_code: '1+268',flag: 'AG.png')
Country.create(ccode: 'AR',name: 'Argentina',isd_code: '54',flag: 'AR.png')
Country.create(ccode: 'AM',name: 'Armenia',isd_code: '374',flag: 'AM.png')
Country.create(ccode: 'AW',name: 'Aruba',isd_code: '297',flag: 'AW.png')
Country.create(ccode: 'AU',name: 'Australia',isd_code: '61',flag: 'AU.png')
Country.create(ccode: 'AT',name: 'Austria',isd_code: '43',flag: 'AT.png')
Country.create(ccode: 'AZ',name: 'Azerbaijan',isd_code: '994',flag: 'AZ.png')
Country.create(ccode: 'BS',name: 'Bahamas',isd_code: '1+242',flag: 'BS.png')
Country.create(ccode: 'BH',name: 'Bahrain',isd_code: '973',flag: 'BH.png')
Country.create(ccode: 'BD',name: 'Bangladesh',isd_code: '880',flag: 'BD.png')
Country.create(ccode: 'BB',name: 'Barbados',isd_code: '1+246',flag: 'BB.png')
Country.create(ccode: 'BY',name: 'Belarus',isd_code: '375',flag: 'BY.png')
Country.create(ccode: 'BE',name: 'Belgium',isd_code: '32',flag: 'BE.png')
Country.create(ccode: 'BZ',name: 'Belize',isd_code: '501',flag: 'BZ.png')
Country.create(ccode: 'BJ',name: 'Benin',isd_code: '229',flag: 'BJ.png')
Country.create(ccode: 'BM',name: 'Bermuda',isd_code: '1+441',flag: 'BM.png')
Country.create(ccode: 'BT',name: 'Bhutan',isd_code: '975',flag: 'BT.png')
Country.create(ccode: 'BO',name: 'Bolivia',isd_code: '591',flag: 'BO.png')
Country.create(ccode: 'BQ',name: 'Bonaire, Sint Eustatius and Saba',isd_code: '599',flag: 'BQ.png')
Country.create(ccode: 'BA',name: 'Bosnia and Herzegovina',isd_code: '387',flag: 'BA.png')
Country.create(ccode: 'BW',name: 'Botswana',isd_code: '267',flag: 'BW.png')
Country.create(ccode: 'BV',name: 'Bouvet Island',isd_code: 'NONE',flag: 'BV.png')
Country.create(ccode: 'BR',name: 'Brazil',isd_code: '55',flag: 'BR.png')
Country.create(ccode: 'IO',name: 'British Indian Ocean Territory',isd_code: '246',flag: 'IO.png')
Country.create(ccode: 'BN',name: 'Brunei',isd_code: '673',flag: 'BN.png')
Country.create(ccode: 'BG',name: 'Bulgaria',isd_code: '359',flag: 'BG.png')
Country.create(ccode: 'BF',name: 'Burkina Faso',isd_code: '226',flag: 'BF.png')
Country.create(ccode: 'BI',name: 'Burundi',isd_code: '257',flag: 'BI.png')
Country.create(ccode: 'KH',name: 'Cambodia',isd_code: '855',flag: 'KH.png')
Country.create(ccode: 'CM',name: 'Cameroon',isd_code: '237',flag: 'CM.png')
Country.create(ccode: 'CA',name: 'Canada',isd_code: '1',flag: 'CA.png')
Country.create(ccode: 'CV',name: 'Cape Verde',isd_code: '238',flag: 'CV.png')
Country.create(ccode: 'KY',name: 'Cayman Islands',isd_code: '1+345',flag: 'KY.png')
Country.create(ccode: 'CF',name: 'Central African Republic',isd_code: '236',flag: 'CF.png')
Country.create(ccode: 'TD',name: 'Chad',isd_code: '235',flag: 'TD.png')
Country.create(ccode: 'CL',name: 'Chile',isd_code: '56',flag: 'CL.png')
Country.create(ccode: 'CN',name: 'China',isd_code: '86',flag: 'CN.png')
Country.create(ccode: 'CX',name: 'Christmas Island',isd_code: '61',flag: 'CX.png')
Country.create(ccode: 'CC',name: 'Cocos (Keeling) Islands',isd_code: '61',flag: 'CC.png')
Country.create(ccode: 'CO',name: 'Colombia',isd_code: '57',flag: 'CO.png')
Country.create(ccode: 'KM',name: 'Comoros',isd_code: '269',flag: 'KM.png')
Country.create(ccode: 'CG',name: 'Congo',isd_code: '242',flag: 'CG.png')
Country.create(ccode: 'CK',name: 'Cook Islands',isd_code: '682',flag: 'CK.png')
Country.create(ccode: 'CR',name: 'Costa Rica',isd_code: '506',flag: 'CR.png')
Country.create(ccode: 'CI',name: 'Cote divoire (Ivory Coast)',isd_code: '225',flag: 'CI.png')
Country.create(ccode: 'HR',name: 'Croatia',isd_code: '385',flag: 'HR.png')
Country.create(ccode: 'CU',name: 'Cuba',isd_code: '53',flag: 'CU.png')
Country.create(ccode: 'CW',name: 'Curacao',isd_code: '599',flag: 'CW.png')
Country.create(ccode: 'CY',name: 'Cyprus',isd_code: '357',flag: 'CY.png')
Country.create(ccode: 'CZ',name: 'Czech Republic',isd_code: '420',flag: 'CZ.png')
Country.create(ccode: 'CD',name: 'Democratic Republic of the Congo',isd_code: '243',flag: 'CD.png')
Country.create(ccode: 'DK',name: 'Denmark',isd_code: '45',flag: 'DK.png')
Country.create(ccode: 'DJ',name: 'Djibouti',isd_code: '253',flag: 'DJ.png')
Country.create(ccode: 'DM',name: 'Dominica',isd_code: '1+767',flag: 'DM.png')
Country.create(ccode: 'DO',name: 'Dominican Republic',isd_code: '1+809, 8',flag: 'DO.png')
Country.create(ccode: 'EC',name: 'Ecuador',isd_code: '593',flag: 'EC.png')
Country.create(ccode: 'EG',name: 'Egypt',isd_code: '20',flag: 'EG.png')
Country.create(ccode: 'SV',name: 'El Salvador',isd_code: '503',flag: 'SV.png')
Country.create(ccode: 'GQ',name: 'Equatorial Guinea',isd_code: '240',flag: 'GQ.png')
Country.create(ccode: 'ER',name: 'Eritrea',isd_code: '291',flag: 'ER.png')
Country.create(ccode: 'EE',name: 'Estonia',isd_code: '372',flag: 'EE.png')
Country.create(ccode: 'ET',name: 'Ethiopia',isd_code: '251',flag: 'ET.png')
Country.create(ccode: 'FK',name: 'Falkland Islands (Malvinas)',isd_code: '500',flag: 'FK.png')
Country.create(ccode: 'FO',name: 'Faroe Islands',isd_code: '298',flag: 'FO.png')
Country.create(ccode: 'FJ',name: 'Fiji',isd_code: '679',flag: 'FJ.png')
Country.create(ccode: 'FI',name: 'Finland',isd_code: '358',flag: 'FI.png')
Country.create(ccode: 'FR',name: 'France',isd_code: '33',flag: 'FR.png')
Country.create(ccode: 'GF',name: 'French Guiana',isd_code: '594',flag: 'GF.png')
Country.create(ccode: 'PF',name: 'French Polynesia',isd_code: '689',flag: 'PF.png')
Country.create(ccode: 'TF',name: 'French Southern Territories',isd_code: '',flag: 'TF.png')
Country.create(ccode: 'GA',name: 'Gabon',isd_code: '241',flag: 'GA.png')
Country.create(ccode: 'GM',name: 'Gambia',isd_code: '220',flag: 'GM.png')
Country.create(ccode: 'GE',name: 'Georgia',isd_code: '995',flag: 'GE.png')
Country.create(ccode: 'DE',name: 'Germany',isd_code: '49',flag: 'DE.png')
Country.create(ccode: 'GH',name: 'Ghana',isd_code: '233',flag: 'GH.png')
Country.create(ccode: 'GI',name: 'Gibraltar',isd_code: '350',flag: 'GI.png')
Country.create(ccode: 'GR',name: 'Greece',isd_code: '30',flag: 'GR.png')
Country.create(ccode: 'GL',name: 'Greenland',isd_code: '299',flag: 'GL.png')
Country.create(ccode: 'GD',name: 'Grenada',isd_code: '1+473',flag: 'GD.png')
Country.create(ccode: 'GP',name: 'Guadaloupe',isd_code: '590',flag: 'GP.png')
Country.create(ccode: 'GU',name: 'Guam',isd_code: '1+671',flag: 'GU.png')
Country.create(ccode: 'GT',name: 'Guatemala',isd_code: '502',flag: 'GT.png')
Country.create(ccode: 'GG',name: 'Guernsey',isd_code: '44',flag: 'GG.png')
Country.create(ccode: 'GN',name: 'Guinea',isd_code: '224',flag: 'GN.png')
Country.create(ccode: 'GW',name: 'Guinea-Bissau',isd_code: '245',flag: 'GW.png')
Country.create(ccode: 'GY',name: 'Guyana',isd_code: '592',flag: 'GY.png')
Country.create(ccode: 'HT',name: 'Haiti',isd_code: '509',flag: 'HT.png')
Country.create(ccode: 'HM',name: 'Heard Island and McDonald Islands',isd_code: 'NONE',flag: 'HM.png')
Country.create(ccode: 'HN',name: 'Honduras',isd_code: '504',flag: 'HN.png')
Country.create(ccode: 'HK',name: 'Hong Kong',isd_code: '852',flag: 'HK.png')
Country.create(ccode: 'HU',name: 'Hungary',isd_code: '36',flag: 'HU.png')
Country.create(ccode: 'IS',name: 'Iceland',isd_code: '354',flag: 'IS.png')
Country.create(ccode: 'IN',name: 'India',isd_code: '91',flag: 'IN.png')
Country.create(ccode: 'ID',name: 'Indonesia',isd_code: '62',flag: 'ID.png')
Country.create(ccode: 'IR',name: 'Iran',isd_code: '98',flag: 'IR.png')
Country.create(ccode: 'IQ',name: 'Iraq',isd_code: '964',flag: 'IQ.png')
Country.create(ccode: 'IE',name: 'Ireland',isd_code: '353',flag: 'IE.png')
Country.create(ccode: 'IM',name: 'Isle of Man',isd_code: '44',flag: 'IM.png')
Country.create(ccode: 'IL',name: 'Israel',isd_code: '972',flag: 'IL.png')
Country.create(ccode: 'IT',name: 'Italy',isd_code: '39',flag: 'IT.png')
Country.create(ccode: 'JM',name: 'Jamaica',isd_code: '1+876',flag: 'JM.png')
Country.create(ccode: 'JP',name: 'Japan',isd_code: '81',flag: 'JP.png')
Country.create(ccode: 'JE',name: 'Jersey',isd_code: '44',flag: 'JE.png')
Country.create(ccode: 'JO',name: 'Jordan',isd_code: '962',flag: 'JO.png')
Country.create(ccode: 'KZ',name: 'Kazakhstan',isd_code: '7',flag: 'KZ.png')
Country.create(ccode: 'KE',name: 'Kenya',isd_code: '254',flag: 'KE.png')
Country.create(ccode: 'KI',name: 'Kiribati',isd_code: '686',flag: 'KI.png')
Country.create(ccode: 'XK',name: 'Kosovo',isd_code: '381',flag: 'XK.png')
Country.create(ccode: 'KW',name: 'Kuwait',isd_code: '965',flag: 'KW.png')
Country.create(ccode: 'KG',name: 'Kyrgyzstan',isd_code: '996',flag: 'KG.png')
Country.create(ccode: 'LA',name: 'Laos',isd_code: '856',flag: 'LA.png')
Country.create(ccode: 'LV',name: 'Latvia',isd_code: '371',flag: 'LV.png')
Country.create(ccode: 'LB',name: 'Lebanon',isd_code: '961',flag: 'LB.png')
Country.create(ccode: 'LS',name: 'Lesotho',isd_code: '266',flag: 'LS.png')
Country.create(ccode: 'LR',name: 'Liberia',isd_code: '231',flag: 'LR.png')
Country.create(ccode: 'LY',name: 'Libya',isd_code: '218',flag: 'LY.png')
Country.create(ccode: 'LI',name: 'Liechtenstein',isd_code: '423',flag: 'LI.png')
Country.create(ccode: 'LT',name: 'Lithuania',isd_code: '370',flag: 'LT.png')
Country.create(ccode: 'LU',name: 'Luxembourg',isd_code: '352',flag: 'LU.png')
Country.create(ccode: 'MO',name: 'Macao',isd_code: '853',flag: 'MO.png')
Country.create(ccode: 'MK',name: 'Macedonia',isd_code: '389',flag: 'MK.png')
Country.create(ccode: 'MG',name: 'Madagascar',isd_code: '261',flag: 'MG.png')
Country.create(ccode: 'MW',name: 'Malawi',isd_code: '265',flag: 'MW.png')
Country.create(ccode: 'MY',name: 'Malaysia',isd_code: '60',flag: 'MY.png')
Country.create(ccode: 'MV',name: 'Maldives',isd_code: '960',flag: 'MV.png')
Country.create(ccode: 'ML',name: 'Mali',isd_code: '223',flag: 'ML.png')
Country.create(ccode: 'MT',name: 'Malta',isd_code: '356',flag: 'MT.png')
Country.create(ccode: 'MH',name: 'Marshall Islands',isd_code: '692',flag: 'MH.png')
Country.create(ccode: 'MQ',name: 'Martinique',isd_code: '596',flag: 'MQ.png')
Country.create(ccode: 'MR',name: 'Mauritania',isd_code: '222',flag: 'MR.png')
Country.create(ccode: 'MU',name: 'Mauritius',isd_code: '230',flag: 'MU.png')
Country.create(ccode: 'YT',name: 'Mayotte',isd_code: '262',flag: 'YT.png')
Country.create(ccode: 'MX',name: 'Mexico',isd_code: '52',flag: 'MX.png')
Country.create(ccode: 'FM',name: 'Micronesia',isd_code: '691',flag: 'FM.png')
Country.create(ccode: 'MD',name: 'Moldava',isd_code: '373',flag: 'MD.png')
Country.create(ccode: 'MC',name: 'Monaco',isd_code: '377',flag: 'MC.png')
Country.create(ccode: 'MN',name: 'Mongolia',isd_code: '976',flag: 'MN.png')
Country.create(ccode: 'ME',name: 'Montenegro',isd_code: '382',flag: 'ME.png')
Country.create(ccode: 'MS',name: 'Montserrat',isd_code: '1+664',flag: 'MS.png')
Country.create(ccode: 'MA',name: 'Morocco',isd_code: '212',flag: 'MA.png')
Country.create(ccode: 'MZ',name: 'Mozambique',isd_code: '258',flag: 'MZ.png')
Country.create(ccode: 'MM',name: 'Myanmar (Burma)',isd_code: '95',flag: 'MM.png')
Country.create(ccode: 'NA',name: 'Namibia',isd_code: '264',flag: 'NA.png')
Country.create(ccode: 'NR',name: 'Nauru',isd_code: '674',flag: 'NR.png')
Country.create(ccode: 'NP',name: 'Nepal',isd_code: '977',flag: 'NP.png')
Country.create(ccode: 'NL',name: 'Netherlands',isd_code: '31',flag: 'NL.png')
Country.create(ccode: 'NC',name: 'New Caledonia',isd_code: '687',flag: 'NC.png')
Country.create(ccode: 'NZ',name: 'New Zealand',isd_code: '64',flag: 'NZ.png')
Country.create(ccode: 'NI',name: 'Nicaragua',isd_code: '505',flag: 'NI.png')
Country.create(ccode: 'NE',name: 'Niger',isd_code: '227',flag: 'NE.png')
Country.create(ccode: 'NG',name: 'Nigeria',isd_code: '234',flag: 'NG.png')
Country.create(ccode: 'NU',name: 'Niue',isd_code: '683',flag: 'NU.png')
Country.create(ccode: 'NF',name: 'Norfolk Island',isd_code: '672',flag: 'NF.png')
Country.create(ccode: 'KP',name: 'North Korea',isd_code: '850',flag: 'KP.png')
Country.create(ccode: 'MP',name: 'Northern Mariana Islands',isd_code: '1+670',flag: 'MP.png')
Country.create(ccode: 'NO',name: 'Norway',isd_code: '47',flag: 'NO.png')
Country.create(ccode: 'OM',name: 'Oman',isd_code: '968',flag: 'OM.png')
Country.create(ccode: 'PK',name: 'Pakistan',isd_code: '92',flag: 'PK.png')
Country.create(ccode: 'PW',name: 'Palau',isd_code: '680',flag: 'PW.png')
Country.create(ccode: 'PS',name: 'Palestine',isd_code: '970',flag: 'PS.png')
Country.create(ccode: 'PA',name: 'Panama',isd_code: '507',flag: 'PA.png')
Country.create(ccode: 'PG',name: 'Papua New Guinea',isd_code: '675',flag: 'PG.png')
Country.create(ccode: 'PY',name: 'Paraguay',isd_code: '595',flag: 'PY.png')
Country.create(ccode: 'PE',name: 'Peru',isd_code: '51',flag: 'PE.png')
Country.create(ccode: 'PH',name: 'Phillipines',isd_code: '63',flag: 'PH.png')
Country.create(ccode: 'PN',name: 'Pitcairn',isd_code: 'NONE',flag: 'PN.png')
Country.create(ccode: 'PL',name: 'Poland',isd_code: '48',flag: 'PL.png')
Country.create(ccode: 'PT',name: 'Portugal',isd_code: '351',flag: 'PT.png')
Country.create(ccode: 'PR',name: 'Puerto Rico',isd_code: '1+939',flag: 'PR.png')
Country.create(ccode: 'QA',name: 'Qatar',isd_code: '974',flag: 'QA.png')
Country.create(ccode: 'RE',name: 'Reunion',isd_code: '262',flag: 'RE.png')
Country.create(ccode: 'RO',name: 'Romania',isd_code: '40',flag: 'RO.png')
Country.create(ccode: 'RU',name: 'Russia',isd_code: '7',flag: 'RU.png')
Country.create(ccode: 'RW',name: 'Rwanda',isd_code: '250',flag: 'RW.png')
Country.create(ccode: 'BL',name: 'Saint Barthelemy',isd_code: '590',flag: 'BL.png')
Country.create(ccode: 'SH',name: 'Saint Helena',isd_code: '290',flag: 'SH.png')
Country.create(ccode: 'KN',name: 'Saint Kitts and Nevis',isd_code: '1+869',flag: 'KN.png')
Country.create(ccode: 'LC',name: 'Saint Lucia',isd_code: '1+758',flag: 'LC.png')
Country.create(ccode: 'MF',name: 'Saint Martin',isd_code: '590',flag: 'MF.png')
Country.create(ccode: 'PM',name: 'Saint Pierre and Miquelon',isd_code: '508',flag: 'PM.png')
Country.create(ccode: 'VC',name: 'Saint Vincent and the Grenadines',isd_code: '1+784',flag: 'VC.png')
Country.create(ccode: 'WS',name: 'Samoa',isd_code: '685',flag: 'WS.png')
Country.create(ccode: 'SM',name: 'San Marino',isd_code: '378',flag: 'SM.png')
Country.create(ccode: 'ST',name: 'Sao Tome and Principe',isd_code: '239',flag: 'ST.png')
Country.create(ccode: 'SA',name: 'Saudi Arabia',isd_code: '966',flag: 'SA.png')
Country.create(ccode: 'SN',name: 'Senegal',isd_code: '221',flag: 'SN.png')
Country.create(ccode: 'RS',name: 'Serbia',isd_code: '381',flag: 'RS.png')
Country.create(ccode: 'SC',name: 'Seychelles',isd_code: '248',flag: 'SC.png')
Country.create(ccode: 'SL',name: 'Sierra Leone',isd_code: '232',flag: 'SL.png')
Country.create(ccode: 'SG',name: 'Singapore',isd_code: '65',flag: 'SG.png')
Country.create(ccode: 'SX',name: 'Sint Maarten',isd_code: '1+721',flag: 'SX.png')
Country.create(ccode: 'SK',name: 'Slovakia',isd_code: '421',flag: 'SK.png')
Country.create(ccode: 'SI',name: 'Slovenia',isd_code: '386',flag: 'SI.png')
Country.create(ccode: 'SB',name: 'Solomon Islands',isd_code: '677',flag: 'SB.png')
Country.create(ccode: 'SO',name: 'Somalia',isd_code: '252',flag: 'SO.png')
Country.create(ccode: 'ZA',name: 'South Africa',isd_code: '27',flag: 'ZA.png')
Country.create(ccode: 'GS',name: 'South Georgia and the South Sandwich Islands',isd_code: '500',flag: 'GS.png')
Country.create(ccode: 'KR',name: 'South Korea',isd_code: '82',flag: 'KR.png')
Country.create(ccode: 'SS',name: 'South Sudan',isd_code: '211',flag: 'SS.png')
Country.create(ccode: 'ES',name: 'Spain',isd_code: '34',flag: 'ES.png')
Country.create(ccode: 'LK',name: 'Sri Lanka',isd_code: '94',flag: 'LK.png')
Country.create(ccode: 'SD',name: 'Sudan',isd_code: '249',flag: 'SD.png')
Country.create(ccode: 'SR',name: 'Suriname',isd_code: '597',flag: 'SR.png')
Country.create(ccode: 'SJ',name: 'Svalbard and Jan Mayen',isd_code: '47',flag: 'SJ.png')
Country.create(ccode: 'SZ',name: 'Swaziland',isd_code: '268',flag: 'SZ.png')
Country.create(ccode: 'SE',name: 'Sweden',isd_code: '46',flag: 'SE.png')
Country.create(ccode: 'CH',name: 'Switzerland',isd_code: '41',flag: 'CH.png')
Country.create(ccode: 'SY',name: 'Syria',isd_code: '963',flag: 'SY.png')
Country.create(ccode: 'TW',name: 'Taiwan',isd_code: '886',flag: 'TW.png')
Country.create(ccode: 'TJ',name: 'Tajikistan',isd_code: '992',flag: 'TJ.png')
Country.create(ccode: 'TZ',name: 'Tanzania',isd_code: '255',flag: 'TZ.png')
Country.create(ccode: 'TH',name: 'Thailand',isd_code: '66',flag: 'TH.png')
Country.create(ccode: 'TL',name: 'Timor-Leste (East Timor)',isd_code: '670',flag: 'TL.png')
Country.create(ccode: 'TG',name: 'Togo',isd_code: '228',flag: 'TG.png')
Country.create(ccode: 'TK',name: 'Tokelau',isd_code: '690',flag: 'TK.png')
Country.create(ccode: 'TO',name: 'Tonga',isd_code: '676',flag: 'TO.png')
Country.create(ccode: 'TT',name: 'Trinidad and Tobago',isd_code: '1+868',flag: 'TT.png')
Country.create(ccode: 'TN',name: 'Tunisia',isd_code: '216',flag: 'TN.png')
Country.create(ccode: 'TR',name: 'Turkey',isd_code: '90',flag: 'TR.png')
Country.create(ccode: 'TM',name: 'Turkmenistan',isd_code: '993',flag: 'TM.png')
Country.create(ccode: 'TC',name: 'Turks and Caicos Islands',isd_code: '1+649',flag: 'TC.png')
Country.create(ccode: 'TV',name: 'Tuvalu',isd_code: '688',flag: 'TV.png')
Country.create(ccode: 'UG',name: 'Uganda',isd_code: '256',flag: 'UG.png')
Country.create(ccode: 'UA',name: 'Ukraine',isd_code: '380',flag: 'UA.png')
Country.create(ccode: 'AE',name: 'United Arab Emirates',isd_code: '971',flag: 'AE.png')
Country.create(ccode: 'GB',name: 'United Kingdom',isd_code: '44',flag: 'GB.png')
Country.create(ccode: 'US',name: 'United States',isd_code: '1',flag: 'US.png')
Country.create(ccode: 'UM',name: 'United States Minor Outlying Islands',isd_code: 'NONE',flag: 'UM.png')
Country.create(ccode: 'UY',name: 'Uruguay',isd_code: '598',flag: 'UY.png')
Country.create(ccode: 'UZ',name: 'Uzbekistan',isd_code: '998',flag: 'UZ.png')
Country.create(ccode: 'VU',name: 'Vanuatu',isd_code: '678',flag: 'VU.png')
Country.create(ccode: 'VA',name: 'Vatican City',isd_code: '39',flag: 'VA.png')
Country.create(ccode: 'VE',name: 'Venezuela',isd_code: '58',flag: 'VE.png')
Country.create(ccode: 'VN',name: 'Vietnam',isd_code: '84',flag: 'VN.png')
Country.create(ccode: 'VG',name: 'Virgin Islands, British',isd_code: '1+284',flag: 'VG.png')
Country.create(ccode: 'VI',name: 'Virgin Islands, US',isd_code: '1+340',flag: 'VI.png')
Country.create(ccode: 'WF',name: 'Wallis and Futuna',isd_code: '681',flag: 'WF.png')
Country.create(ccode: 'EH',name: 'Western Sahara',isd_code: '212',flag: 'EH.png')
Country.create(ccode: 'YE',name: 'Yemen',isd_code: '967',flag: 'YE.png')
Country.create(ccode: 'ZM',name: 'Zambia',isd_code: '260',flag: 'ZM.png')
Country.create(ccode: 'ZW',name: 'Zimbabwe',isd_code: '263',flag: 'ZW.png')

DealStatus.create(:name => "Incoming",:organization_id => 1,:original_id => 1)
DealStatus.create(:name => "Qualified",:organization_id => 1,:original_id => 2)
DealStatus.create(:name => "Not Qualified",:organization_id => 1,:original_id => 3)
DealStatus.create(:name => "Won",:organization_id => 1,:original_id => 4)
DealStatus.create(:name => "Lost",:organization_id => 1,:original_id => 5)
DealStatus.create(:name => "Junk",:organization_id => 1,:original_id => 6)
DealStatus.create(:name => "No Contact",:organization_id => 1,:original_id => 7)
DealStatus.create(:name => "Follow Up Require",:organization_id => 1,:original_id => 8)
DealStatus.create(:name => "Follow Up",:organization_id => 1,:original_id => 9)
DealStatus.create(:name => "Quoted",:organization_id => 1,:original_id => 10)
DealStatus.create(:name => "Meeting Scheduled",:organization_id => 1,:original_id => 11)
DealStatus.create(:name => "Forecasted",:organization_id => 1,:original_id => 12)
DealStatus.create(:name => "Waiting For Project",:organization_id => 1,:original_id => 13)
DealStatus.create(:name => "Proposal",:organization_id => 1,:original_id => 14)
DealStatus.create(:name => "Estimate",:organization_id => 1,:original_id => 15)


PriorityType.create(:name => "Hot",:organization_id => 1,:original_id => 1)
PriorityType.create(:name => "Warm",:organization_id => 1,:original_id => 2)
PriorityType.create(:name => "Cold",:organization_id => 1,:original_id => 3)



TaskType.create(:name => "Appointment",:organization_id => 1)
TaskType.create(:name => "Billing",:organization_id => 1)
TaskType.create(:name => "Documentation",:organization_id => 1)
TaskType.create(:name => "Follow-up",:organization_id => 1)
TaskType.create(:name => "Meeting",:organization_id => 1)
TaskType.create(:name => "None",:organization_id => 1)
TaskType.create(:name => "Quote",:organization_id => 1)
TaskType.create(:name => "Thank-you",:organization_id => 1)
